### ISSUE TITLE
doesn't work after valkyrie update

### ISSUE THREAD

**Issue by adem940** [meishuu/tera-proxy#10]
it shows connected but proxy doesn't change anything :/

**Comment by adem940** [comment]
got it working :)

**Comment by MalaNL** [comment]
Care to eleborate your fix? Perhaps you could make a pull request.

**Comment by adem940** [comment]
@Malalicious download tera proxy 54.1 (latest one), copy the servers.json file from your old proxy/bin folder and past it into this new proxy/bin folder, I don't know why but this new one doesn't have all servers on NA so you need the servers.json file from old proxy folder, after that run the ''rub.bat'' file in bin as admin and it should work, make sure not to run launcher before running proxy.
