### ISSUE TITLE
Doesn't work after Valkyrie update...

### ISSUE THREAD

**Issue by andy1228** [meishuu/tera-proxy#11]
Mine isn't working after valk update :( any tips on how to fix it?

**Comment by Chocological** [comment]
I can confirm this issue. Most notably affected skill is archer's rapid fire skill. It just seems like the packet injection doesn't work anymore even though the proxy servers are there.

**Comment by Malalicious** [comment]
This was already mentioned in issue #10. Potential fix given by creator of the issue.

**Comment by Chocological** [comment]
I actually tried out his steps before posting my confirmation of the aforementioned issues. The latest version of the tera proxy still doesn't work for me.

**Comment by meishuu** [comment]
Could you perhaps upload your `baldera.log` somewhere? You can link it here, or attach it in email or Discord DM if you'd prefer.

**Comment by Chocological** [comment]
I have emailed you my baldera.log file for your reference. Thanks in advance for the review!

**Comment by meishuu** [comment]
Hm. I suppose it's worth adding a little more stuff to log when I update things.

Thank you for the log. I'm not seeing any modules loaded. Are you **absolutely certain** that:
* you moved over your old `node_modules` correctly, and
* you are connecting to a proxied server?

If you're at all unsure about the latter, a look at your `servers.json` might help.

**Comment by Chocological** [comment]
It worked like a charm. I'm now kicking myself for not realizing that i hadn't transferred my old modules over. Thanks for the advice!

**Comment by meishuu** [comment]
👌

Now we wait for @andy1228 and if there's nothing in a few days we'll go ahead and close this issue.

**Comment by andy1228** [comment]
@meishuu It works for me now! Thank you for your help! :+1:
