### ISSUE TITLE
Skills not working after pressing the skill button

### ISSUE THREAD

**Issue by RandomSharky** [meishuu/tera-proxy#12]
Sometimes the skills don't want to activate like Radiant Arrow or Arcane Pulse. Without teraproxy I didn't had any problems with that. Everything else is working.

**Comment by RandomSharky** [comment]
Sometimes Hailstorm animation goes off but the skill didn't activate.

**Comment by Miei** [comment]
I don't think this is an issue with `tera-proxy` itself. Most likely you are using some module like [pinkipi/skill-prediction](https://github.com/pinkipi/skill-prediction). If that's the case, you'll find more appropriate support there, not here.

**Comment by adem940** [comment]
it happens to me too sometimes, especially on mystic while summoning warding totem, you gotta press the button slowly a bit, and as Miei said, I am using pinkipi's skill prediction, so you can create an issue there.

**Comment by meishuu** [comment]
As mentioned, this is with Pinkie Pie's `skill-prediction`, so create an issue there if you are still having problems:

https://github.com/pinkipi/skill-prediction/issues
