### ISSUE TITLE
How to run Tera proxy? 

### ISSUE THREAD

**Issue by Skyhawkx3** [meishuu/tera-proxy#13]
Hello there!  
So I heard about Tera proxy and how it makes the actions take much less time so I was missing around trying to get it to work but without luck ... I tried the solution in post #9  but I keep getting server not found and stuff...

is there any guide on how to setup this program for EU? Because I can't find any posts when I try to google it?
or if someone can elaborate or share his version with me

**Comment by Malalicious** [comment]
Where exactly do you get the error message saying server not found? Does tera-proxy give this output? Does the TERA launcher show this message? Need a little bit more information

**Comment by Skyhawkx3** [comment]
This is the error I'm getting
http://prntscr.com/f22hna

What I did exactly is

1-Downloaded Tera Proxy ( latest version )
2- Edited the Line 19 of index.js in the folder tera-proxy-sls and changed the url from the enmasse to this one http://web-sls.tera.gameforge.com:4566/servers/list.uk.
3-Edited Line 17, 140 and 157 of proxy.js in the bin folder and changed 3 links from sls.service.enmasse.com to web-sls.tera.gameforge.com

That's excatly what I did only --- to get that error message

I'm playing Tera EU - Gameforge

Do I need to edit in my IP or client IP orr something? I'm not a pro so the more details the betterr

thanks in advance

**Comment by Malalicious** [comment]
You need to change the servers.json file with the correct server IDs found on the web-sls page. Change the IDs (and optionally the names) and you're good to go.

**Comment by Skyhawkx3** [comment]
for those who are interested.
this is what you edit in servers.json

{ "26":
  { "name": "(INT) - Killian"
  , "port": 7801
  }
}

if you are from killian EU

**Comment by manecasfx14** [comment]
it didnt work for me..i did all steps  

1-Downloaded Tera Proxy ( latest version 54.1)
2- Edited the Line 19 of index.js in the folder tera-proxy-sls and changed the url from the enmasse to this one http://web-sls.tera.gameforge.com:4566/servers/list.uk.
3-Edited Line 17, 140 and 157 of proxy.js in the bin folder and changed 3 links from sls.service.enmasse.com to web-sls.tera.gameforge.com

and the servers.json file with my server id

{ "27":
{ "name": "(EN) - Mystel"
, "port": 7802
}

but still says server not founder when i run the tera proxy

**Comment by meishuu** [comment]
Closing this issue since it's for an outdated version of the proxy. v1.0.0 should handle this fine, *and* installation instructions are on the website: <https://meishuu.github.io/tera-proxy/user-guide>
