### ISSUE TITLE
Unmapped protocol 313624 (VSH patch)

### ISSUE THREAD

**Issue by wanngjin12** [meishuu/tera-proxy#21]
![tim 20170604115024](https://cloud.githubusercontent.com/assets/29174821/26760922/0950bb10-491c-11e7-8abe-7834efb7c17f.jpg)

It keeps showing this error message after the latest patch on TW server.
Only one module was installed and I tried re-install both the proxy and the module several times but it doesn't work at all.

**Comment by Every-L** [comment]
Fetch opcode and change your opcode in the tera-data folder.

**Comment by Voups** [comment]
How can I do this, can you help me?

**Comment by meishuu** [comment]
Here's the latest announcement from the Discord server:

---

I haven't met any of my personal proxy deadlines for this patch but here's an \~emergency update\~ for the people that just want something out of the box. Here's the files for Lakan's Fury patch, same installation instructions as before (you can definitely just unzip and overwrite files for this one): <https://github.com/meishuu/tera-proxy/releases/tag/v1.0.0-tera56> Don't forget to move `config.yml` over if needed.

**If you use Pinkie Pie's skill prediction, get the download from their Discord instead.** When I have a little more time we should be able to consolidate these.

If you don't want to go through the full trouble of downloading the whole thing again, the upgrade step is just downloading the new `tera-data` @ <https://github.com/meishuu/tera-data/archive/master.zip>, unzipping it, and then overwriting `tera-proxy/node_modules/tera-data` with the new one. That's it!

The prepackaged bundle also includes node 8.0.0 just to keep everything up to date. **This huge update to Node.js was released literally seven days ago** so if you are concerned about stability, or you have one of those weird problems that appear to be solved by node 6?, feel free to keep your old `tera-proxy/bin/node.exe`, or whatever works for your setup.

I have not gotten around to resolving the lingering issues with EACCES on port 80 and whatever it is people are getting with the XML `&copy;` error. If you need these fixed, instructions are still in the announcement directly above this one. (You can add multiple regions between the brackets by separating them with a comma.)

That's it for now. The final tumblr post has been waiting in an unfinished draft. You're just going to have to wait for life to stop kicking me in the arse and I'll patch up proxy things and finally publish that concluding post. Until then, **good luck with VSH!**
