### ISSUE TITLE
ERROR [tera patch 56]

### ISSUE THREAD

**Issue by Notmacro** [meishuu/tera-proxy#22]
![4444444](https://cloud.githubusercontent.com/assets/29227580/26825853/47423ec2-4abf-11e7-9aa7-d9f831b99337.jpg)

**Comment by notaslayer** [comment]
any fix on this probleM?

**Comment by NXLinny** [comment]
Im having this error too, probably its because the dungeon update that they released today. Maybe someone will need to release a update for the proxy to work again. : (

**Comment by wuaw** [comment]
Update has been available for this protocol version for 2 days now, please update [tera-data](https://github.com/meishuu/tera-data) located in `tera-proxy/node_modules/tera-data`

**Comment by erikbernardo** [comment]
I'm getting an error after update as well, but slightly different:

ERROR tera-proxy-sls: xml parser error
[xmldom error]  entity not found:&copy;

clues?

**Comment by meishuu** [comment]
Duplicate of #21. See my comment there for details.

@erikbernardo Please feel free to open an issue for that error if it is preventing the proxy from working.

**Comment by erikbernardo** [comment]
great, many thanks @meishuu .
