### ISSUE TITLE
Skillcasting error

### ISSUE THREAD

**Issue by Katanyanmo** [meishuu/tera-proxy#23]
After update skills not working, even it doesn't show if you use skill (coming to CD shows btw).
![skillcasting](https://user-images.githubusercontent.com/29236127/26844875-853faa8c-4afd-11e7-99a2-be4188c9fd94.png)

Recently updated node to last version.

**Comment by Every-L** [comment]
as far as I tested, the new 'tera-data' contains bug 'protocol'. Simplest fix on this problem is to rollback the protocol folder in the tera-data folder. I don't know which one is wrong because I was using old tera-data folder and manually changing opcode so far.

**Comment by Katanyanmo** [comment]
SOLVED
Updated the newest protocol and not it works.
