### ISSUE TITLE
Don't work on RU Server "unmapped protocol version 328425" Error

### ISSUE THREAD

**Issue by NeruGaDzaa** [meishuu/tera-proxy#55]
After the last update, stopped working, gives an error "unmapped protocol version 328425", the tera-date was updated
![2](https://user-images.githubusercontent.com/37372632/37405590-b4de4082-279d-11e8-834e-7a88cd53fb27.PNG)

**Comment by Mister-Kay** [comment]
Fixed. Yeah every patch requires a new map of the protocol.

**Comment by NeruGaDzaa** [comment]
and the fact is that I updated the tera-proxy to the current version

**Comment by NeruGaDzaa** [comment]
That decides me.
